datadog:
  logs:
    enabled: true
    containerCollectAll: false
    containerExcludeLogs:
      - "name:datadog-agent"
  site: datadoghq.eu
  clusterName: dust-kube

  apm:
    socketEnabled: false
    portEnabled: true

  dogstatsd:
    useDogStatsDSocketVolume: false
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

  ignoreAutoConfig:
    - cilium
    - nginx
    - redis

  kubeStateMetricsCore:
    enabled: true

  kubeStateMetricsEnabled: false

prometheusScrape:
    enabled: true
    serviceEndpoints: true

confd:
  prometheus.yaml: |
    init_config:
    instances:
      - prometheus_url: https://gmnlm.tmprl.cloud/prometheus
        namespace: "dust-front-prod.gmnlm"
        metrics:
          - temporal_cloud_v0_workflow_failed_count
          - temporal_cloud_v0_workflow_timeout_count
          - temporal_cloud_v0_workflow_cancel_count
        ssl_cert: /etc/certs/temporal-datadog.crt
        ssl_private_key: /etc/certs/temporal-datadog-cert.key

clusterAgent:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  replicas: 2
  createPodDisruptionBudget: true

agents:
  priorityClassCreate: true
  containers:
    agent:
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
      env:
        - name: DD_ADDITIONAL_CONFIG_PROVIDERS
          value: "confd"
      volumeMounts:
        - name: confd
          mountPath: /confd
        - name: cert-volume
          mountPath: /etc/certs
  volumes:
    - name: confd
      configMap:
        name: datadog-confd
    - name: cert-volume
      secret:
        secretName: temporal-datadog-cert

providers:
  gke:
    autopilot: true
