apiVersion: v1
kind: Service
metadata:
  name: discourse-service
spec:
  selector:
    app: discourse
    name: discourse-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
  type: ClusterIP